
#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED
/**
   The plugin name.@n
   This is used to identify your plugin before a Plugin instance can be created.
   @note This macro is required.
 */
#define DISTRHO_PLUGIN_NAME "thunderOx_triceratops"

/**
   Number of audio inputs the plugin has.
   @note This macro is required.
 */
#define DISTRHO_PLUGIN_NUM_INPUTS 0

/**
   Number of audio outputs the plugin has.#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED
   @note This macro is required.
 */
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2

/**
   The plugin URI when exporting in LV2 format.
   @note This macro is required.
 */
#define DISTRHO_PLUGIN_URI "http://thunderox.com/thunderOx_triceratops"

/**
   Wherever the plugin has a custom %UI.
   @see DISTRHO_UI_USE_NANOVG
   @see UI
 */
#define DISTRHO_PLUGIN_HAS_UI 1

/**
   Wherever the plugin processing is realtime-safe.@n
   TODO - list rtsafe requirements
 */
#define DISTRHO_PLUGIN_IS_RT_SAFE 1

/**
   Wherever the plugin is a synth.@n
   @ref DISTRHO_PLUGIN_WANT_MIDI_INPUT is automatically enabled when this is too.
   @see DISTRHO_PLUGIN_WANT_MIDI_INPUT
 */
#define DISTRHO_PLUGIN_IS_SYNTH 1

/**
   Enable direct access between the %UI and plugin code.
   @see UI::getPluginInstancePointer()
   @note DO NOT USE THIS UNLESS STRICTLY NECESSARY!!
         Try to avoid it at all costs!
 */
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 0

/**
   Wherever the plugin introduces latency during audio or midi processing.
   @see Plugin::setLatency(uint32_t)
 */
#define DISTRHO_PLUGIN_WANT_LATENCY 0

/**
   Wherever the plugin wants MIDI input.@n
   This is automatically enabled if @ref DISTRHO_PLUGIN_IS_SYNTH is true.
 */
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1

/**
   Wherever the plugin wants MIDI output.
   @see Plugin::writeMidiEvent(const MidiEvent&)
 */
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 0

/**
   Wherever the plugin provides its own internal programs.
   @see Plugin::initProgramName(uint32_t, String&)
   @see Plugin::loadProgram(uint32_t)
 */
#define DISTRHO_PLUGIN_WANT_PROGRAMS 0

/**
   Wherever the plugin uses internal non-parameter data.
   @see Plugin::initState(uint32_t, String&, String&)
   @see Plugin::setState(const char*, const char*)
 */
#define DISTRHO_PLUGIN_WANT_STATE 0

/**
   Wherever the plugin wants time position information from the host.
   @see Plugin::getTimePosition()
 */
#define DISTRHO_PLUGIN_WANT_TIMEPOS 1

/**
   Wherever the %UI uses NanoVG for drawing instead of the default raw OpenGL calls.@n
   When enabled your %UI instance will subclass @ref NanoWidget instead of @ref Widget.
 */
#define DISTRHO_UI_USE_NANOVG 0

/**
   The %UI URI when exporting in LV2 format.@n
   By default this is set to @ref DISTRHO_PLUGIN_URI with "#UI" as suffix.
 */
#define DISTRHO_UI_URI DISTRHO_PLUGIN_URI "#UI"

enum Parameters {
	kParameterBufferSize = 0,
	kParametertriceratopsTime,
	kParametertriceratopsAmount,
	kParametertriceratopsVolume,
	kParametertriceratops_FilterType,
	kParametertriceratops_FilterFrequency,
	kParametertriceratops_FilterResonance,
    
	TRICERATOPS_OUT_LEFT,
	TRICERATOPS_OUT_RIGHT,
	TRICERATOPS_CONTROL,

	TRICERATOPS_MASTER_VOLUME,
	TRICERATOPS_MASTER_TUNE,
	TRICERATOPS_AMP_DRIVE,
	TRICERATOPS_FILTER_MODE,
	TRICERATOPS_CUTOFF,
	TRICERATOPS_RESONANCE,
	TRICERATOPS_FILTER_KEY_FOLLOW,
	TRICERATOPS_LEGATO,
	TRICERATOPS_SYNC,
	TRICERATOPS_WARMTH,
	TRICERATOPS_FM,
	TRICERATOPS_PANIC,

	TRICERATOPS_OSC1_ACTIVE,
	TRICERATOPS_OSC1_VOLUME,
	TRICERATOPS_OSC1_PULSEWIDTH,
	TRICERATOPS_OSC1_WAVE,
	TRICERATOPS_OSC1_OCTAVE,
	TRICERATOPS_OSC1_DETUNE,
	TRICERATOPS_OSC1_DETUNE_CENTRE,
	TRICERATOPS_OSC1_INERTIA,

	TRICERATOPS_OSC2_ACTIVE,
	TRICERATOPS_OSC2_VOLUME,
	TRICERATOPS_OSC2_PULSEWIDTH,
	TRICERATOPS_OSC2_WAVE,
	TRICERATOPS_OSC2_OCTAVE,
	TRICERATOPS_OSC2_DETUNE,
	TRICERATOPS_OSC2_DETUNE_CENTRE,
	TRICERATOPS_OSC2_INERTIA,

	TRICERATOPS_OSC3_ACTIVE,
	TRICERATOPS_OSC3_VOLUME,
	TRICERATOPS_OSC3_PULSEWIDTH,
	TRICERATOPS_OSC3_WAVE,
	TRICERATOPS_OSC3_OCTAVE,
	TRICERATOPS_OSC3_DETUNE,
	TRICERATOPS_OSC3_DETUNE_CENTRE,
	TRICERATOPS_OSC3_INERTIA,

	TRICERATOPS_ADSR1_ATTACK,
	TRICERATOPS_ADSR1_DECAY,
	TRICERATOPS_ADSR1_SUSTAIN,
	TRICERATOPS_ADSR1_RELEASE,
	TRICERATOPS_ADSR1_ROUTE_ONE,
	TRICERATOPS_ADSR1_ROUTE_ONE_DEST,
	TRICERATOPS_ADSR1_ROUTE_TWO,
	TRICERATOPS_ADSR1_ROUTE_TWO_DEST,

	TRICERATOPS_ADSR2_ATTACK,
	TRICERATOPS_ADSR2_DECAY,
	TRICERATOPS_ADSR2_SUSTAIN,
	TRICERATOPS_ADSR2_RELEASE,
	TRICERATOPS_ADSR2_ROUTE_ONE,
	TRICERATOPS_ADSR2_ROUTE_ONE_DEST,
	TRICERATOPS_ADSR2_ROUTE_TWO,
	TRICERATOPS_ADSR2_ROUTE_TWO_DEST,

	TRICERATOPS_ADSR3_ATTACK,
	TRICERATOPS_ADSR3_DECAY,
	TRICERATOPS_ADSR3_SUSTAIN,
	TRICERATOPS_ADSR3_RELEASE,
	TRICERATOPS_ADSR3_LFO1_AMOUNT,
	TRICERATOPS_ADSR3_LFO2_AMOUNT,
	TRICERATOPS_ADSR3_LFO3_AMOUNT,

	TRICERATOPS_LFO1_RETRIG,
	TRICERATOPS_LFO1_SPEED,
	TRICERATOPS_LFO1_WAVE,
	TRICERATOPS_LFO1_DCO1_PITCH,
	TRICERATOPS_LFO1_DCO2_PITCH,
	TRICERATOPS_LFO1_DCO3_PITCH,
	TRICERATOPS_LFO1_FILTER,
	TRICERATOPS_LFO1_ROUTE_ONE,
	TRICERATOPS_LFO1_ROUTE_ONE_DEST,
	TRICERATOPS_LFO1_ROUTE_TWO,
	TRICERATOPS_LFO1_ROUTE_TWO_DEST,

	TRICERATOPS_LFO2_RETRIG,
	TRICERATOPS_LFO2_SPEED,
	TRICERATOPS_LFO2_WAVE,
	TRICERATOPS_LFO2_DCO1_PITCH,
	TRICERATOPS_LFO2_DCO2_PITCH,
	TRICERATOPS_LFO2_DCO3_PITCH,
	TRICERATOPS_LFO2_FILTER,
	TRICERATOPS_LFO2_ROUTE_ONE,
	TRICERATOPS_LFO2_ROUTE_ONE_DEST,
	TRICERATOPS_LFO2_ROUTE_TWO,
	TRICERATOPS_LFO2_ROUTE_TWO_DEST,

	TRICERATOPS_LFO3_RETRIG,
	TRICERATOPS_LFO3_SPEED,
	TRICERATOPS_LFO3_WAVE,
	TRICERATOPS_LFO3_DCO1_PITCH,
	TRICERATOPS_LFO3_DCO2_PITCH,
	TRICERATOPS_LFO3_DCO3_PITCH,
	TRICERATOPS_LFO3_FILTER,
	TRICERATOPS_LFO3_ROUTE_ONE,
	TRICERATOPS_LFO3_ROUTE_ONE_DEST,
	TRICERATOPS_LFO3_ROUTE_TWO,
	TRICERATOPS_LFO3_ROUTE_TWO_DEST,

	TRICERATOPS_FX_ECHO_ACTIVE,
	TRICERATOPS_FX_ECHO_SPEED,
	TRICERATOPS_FX_ECHO_DECAY,
	TRICERATOPS_FX_ECHO_EQ_LOW,
	TRICERATOPS_FX_ECHO_EQ_MID,
	TRICERATOPS_FX_ECHO_EQ_HIGH,

	TRICERATOPS_UNISON_ACTIVATE,
	TRICERATOPS_UNISON_ONE,
	TRICERATOPS_UNISON_TWO,
	TRICERATOPS_UNISON_THREE,

	TRICERATOPS_MODIFIER_DIRT,

	TRICERATOPS_FX_REVERB_ACTIVE,
	TRICERATOPS_FX_REVERB_DECAY,
	TRICERATOPS_FX_REVERB_MIX,

	TRICERATOPS_MODIFIER_STEREO_MODE,
	TRICERATOPS_OSC1_PAN,
	TRICERATOPS_OSC2_PAN,
	TRICERATOPS_OSC3_PAN,
	TRICERATOPS_MODIFIER_RING,

	TRICERATOPS_PRESET_CATEGORY,
	TRICERATOPS_PITCH_BEND_RANGE,
	TRICERATOPS_MIDI_CHANNEL,
        
	kParameterCount
};



#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED
